name: dependencies
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  shift_ui:
    git:
      url: git@github.com:ShiftGroupLtd/shift-partner-app.git
      path: shift_ui
      ref: dependency-manager

