name: base_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  micro_core:
    path: ../micro_core
  login:
    path: ../micro_apps/login
  home:
    path: ../micro_apps/home
  search:
    path: ../micro_apps/search
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
